/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetocalculadoraemjavaprisci;

public class App {
    
    public static void main(String[] args){
        Calculadora calc = new Calculadora();
        System.out.println(calc.somar(6, 3));
        System.out.println(calc.subtrair(6, 3));
        System.out.println(calc.multiplicar(6, 3));
        System.out.println(calc.dividir(6, 3));
    }
}
